// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awicytvarfwydeebjivk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aWN5dHZhcmZ3eWRlZWJqaXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjk4ODksImV4cCI6MjA2NTk0NTg4OX0.EVr5bMRyM3m8iJm2wmJdjujfilFvpIGhboAZ6AJzrDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);